[book]
authors = ["Phosphorus-M"]
language = "es"
languages = ["es", "en"]
multilingual = true
src = "src"
title = "Rust para Go Devs"


[language.en]
name = "English"
[language.es]
name = "Español"

[output.html.code.hidelines]
rust = "#"
go = "#"

[preprocessor.pagetoc]

[output.html.playground]
editable = true


[output.html]
site-url = "https://go-book.rustlang-es.org"
git-repository-url = "https://github.com/RustLangES/rust-para-go-devs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/RustLangES/rust-para-go-devs/edit/main/{path}"
additional-css = ["theme/extra.css", "theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]